engines:
  rubocop:
    enabled: true
  golint:
    enabled: true
  fixme:
    enabled: true
  eslint:
    enabled: true
  # ... CONFIG CONTENT ...
  scss-lint:
    enabled: true
    # ... CONFIG CONTENT ...
    checks:
      SelectorDepth:
        enabled: false
      NestingDepth:
        enabled: false
      ColorVariable:
        enabled: false
# ... CONFIG CONTENT ...
ratings:
  paths:
  - app/**
  - lib/**
  - "**.rb"
  - "**.go"
exclude_paths:
- spec/**/*
- vendor/**/*
- js/jquery.js
- js/bootstrap.js
- js/bootstrap.min.js
- css/bootstrap.css
- css/bootstrap.css.map
- css/bootstrap.min.css
- css/normalize.css
- config.rb
- css/bootstrap-theme.css
- css/bootstrap-theme.min.css