engines:
  rubocop:
    enabled: true
  golint:
    enabled: true
  jslint:
    enabled: true
  eslint:
    enabled: true
  scss-lint:
    enabled: true
ratings:
  paths:
  - app/**
  - lib/**
  - "**.rb"
  - "**.go"
exclude_paths:
- spec/**/*
- vendor/**/*
- js/bootstrap.js
- js/bootstrap.min.js
- css/bootstrap.css
- css/bootstrap.css.map
- css/bootstrap.min.css
- css/normalize.css
- config.rb
- css/bootstrap-theme.css
- css/bootstrap-theme.min.css